version: '3'

services:
  web:
    hostname: service
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile_express
    command: /home_automation/entrypoint.sh
    volumes:
      - .:/home_automation
      - /dev/bus/usb:/dev/bus/usb
      - ../kalliope/kalliope:/usr/local/lib/python2.7/dist-packages/kalliope
      # - ./sphinx/sphinxsearch:/etc/sphinxsearch
      # - ./sphinx/data://var/lib/sphinxsearch/data
    ports:
      - "80:5000"
    privileged: true
#     depends_on:
#       - db
#     links:
#       - db
# # docker run -it --privileged -v /dev/bus/usb:/dev/bus/usb -v /my_project_repos/kalliope_starter_en:/starter kalliope bash
#   db:
#     image: mariadb
#     restart: always
#     volumes:
#       - ./docker/mysql_data:/var/lib/mysql
#     ports:
#       - 3306
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
